---
- name: Install i3 Desktop Build
  hosts: desktop
  gather_facts: yes
# TODO add sudo password to a vault
  tasks:
  - name: Include vars
    include_vars:
      file: vars.yaml
      

  - name: Update all packages
    dnf:
      state: latest
      name: '*'
    become: yes

  - name: Copy non repo packages
    copy:
      dest: /tmp/
      src: "./files/{{ item }}"
    with_items: "{{ non_repo_packages }}"

  - name: Install non repo packages
    dnf:
      state: present
      name: "/tmp/{{ item }}"
    become: yes
    with_items: "{{ non_repo_packages }}"

  - name: Install additional packages
    dnf:
      name: compton
      state: present
    become: yes

  - name: Copy i3-config
    copy:
      dest: ~/.config/i3/
      src: ./files/i3-config
    
  - name: Copy systemd unit files
    copy:
      dest: "{{ systemd_location }}"
      src: ./files/systemd/
    become: yes

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    become: yes